	CREATE TABLE DEPARTMENT(
	   ID INT PRIMARY KEY      NOT NULL,
	   DEPT           CHAR(50) NOT NULL,
	   EMP_ID         INT      NOT NULL
	);

CREATE TABLE users (
	username TEXT PRIMARY KEY NOT NULL,
	password TEXT NOT NULL
);